apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.apiKeySecretName" . }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
type: Opaque
data:
  OSTARA_AGENT_MAIN_API_KEY: {{ randAlphaNum 20 | b64enc | quote }}