apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo.fullname" . }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.managementPort }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    {{- include "demo.selectorLabels" . | nindent 4 }}
