
name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - charts/**/Chart.yaml
      - .github/workflows/publish-helm.yml
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "ops@krud.dev"
          git config --global user.name "krud.dev Ops"

      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"